spring.application.name=secure-credential-organizer

# ==============================
# ACTIVE PROFILE
# ==============================
spring.profiles.active=local

# ==============================
# SERVER
# ==============================
server.port=8080

# ==============================
# JPA CONFIGURATION
# ==============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# FLYWAY MIGRATION
# ==============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# ==============================
# JWT CONFIGURATION
# ==============================
jwt.secret=${JWT_SECRET:NWQ3YjQ4MjY2ZjYxMGMwY2Y1ZmRkMmY4YjE4YTY4M2Q0NmFkMzQ5MmQ2OTY5M2Y5Y2E0MjM2N2JhYjFlN2NmYjUyZjRmMTViNmQ2YjE0MTRkNjJhY2QxZmI4YjJmNDM2MzQ2NGY=}
jwt.expiration=86400000

# ==============================
# MAIL CONFIGURATION
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==============================
# AES ENCRYPTION
# ==============================
aes.secret-key=${AES_SECRET_KEY:MySecretKey12345}
aes.vault-token-keys=${AES_VAULT_TOKEN_KEYS:12345678901234567890123456789012}
# ==============================
# KDF CONFIGURATION (Argon2id)
# ==============================
argon2.iterations=3
argon2.memory-kb=65536
argon2.parallelism=4

